export const GET_EDU_LIST 	 = 'GET_EDU_LIST'
export const EDU_LIST_DELETE = 'EDU_LIST_DELETE'
export const SET_IS_FROM_SUBMIT_TRUE  = 'SET_IS_FROM_SUBMIT_TRUE'
export const SET_IS_FROM_SUBMIT_FALSE = 'SET_IS_FROM_SUBMIT_FALSE'