export const GET_ADVICE_LIST = 'GET_ADVICE_LIST'
export const ADVICE_LIST_SHOW = 'ADVICE_LIST_SHOW'
export const PICKER_CONFIRM = 'PICKER_CONFIRM'
export const ADVICE_TYPE_PICKER_OPEN = 'ADVICE_TYPE_PICKER_OPEN'