export const NOW_INIT 					 = 'NOW_INIT'
export const SET_CONTENT				 = 'SET_CONTENT'
export const SET_CHECKBOX				 = 'SET_CHECKBOX'
export const PICKER_CONFIRM				 = 'PICKER_CONFIRM'
export const HEAD_NURSE_NAME_PICKER_OPEN = 'HEAD_NURSE_NAME_PICKER_OPEN'
export const SUBMIT_START 				 = 'SUBMIT_START'
export const SUBMIT_DONE 				 = 'SUBMIT_DONE'
export const SHOW_MESSAGE 				 = 'SHOW_MESSAGE'

// // 一般资料
// export const GENERAL_HOSPITALIZEDTYPE_PICKER_OPEN = 'GENERAL_HOSPITALIZEDTYPE_PICKER_OPEN'
// export const GENERAL_EDUCATION_PICKER_OPEN 		  = 'GENERAL_EDUCATION_PICKER_OPEN'
// export const GENERAL_ETHNICGROUP_PICKER_OPEN 	  = 'GENERAL_ETHNICGROUP_PICKER_OPEN'
// export const GENERAL_FAITHS_PICKER_OPEN 		  = 'GENERAL_FAITHS_PICKER_OPEN'
// export const GENERAL_PASTILLNESS_SWITCH_CHANGE 	  = 'GENERAL_PASTILLNESS_SWITCH_CHANGE'
// export const GENERAL_FAMILIAL_SWITCH_CHANGE 	  = 'GENERAL_FAMILIAL_SWITCH_CHANGE'
// export const GENERAL_ALLERGIC_SWITCH_CHANGE 	  = 'GENERAL_ALLERGIC_SWITCH_CHANGE'
// export const GENERAL_CATHETER_SWITCH_CHANGE 	  = 'GENERAL_CATHETER_SWITCH_CHANGE'
// export const GENERAL_HOBBY_SWITCH_CHANGE 		  = 'GENERAL_HOBBY_SWITCH_CHANGE'
// 
// // 生活自理
// export const SELF_HELP_NUTRITION_PICKER_OPEN 		  = 'SELF_HELP_NUTRITION_PICKER_OPEN'
// export const SELF_HELP_DIETING_MODE_PICKER_OPEN 	  = 'SELF_HELP_DIETING_MODE_PICKER_OPEN'
// export const SELF_HELP_SMOKE_PICKER_OPEN 			  = 'SELF_HELP_SMOKE_PICKER_OPEN'
// export const SELF_HELP_DRINK_PICKER_OPEN 			  = 'SELF_HELP_DRINK_PICKER_OPEN'
// export const SELF_HELP_URINATION_PICKER_OPEN 		  = 'SELF_HELP_URINATION_PICKER_OPEN'
// export const SELF_HELP_URINE_PICKER_OPEN 			  = 'SELF_HELP_URINE_PICKER_OPEN'
// export const SELF_HELP_DEFECATE_PICKER_OPEN 		  = 'SELF_HELP_DEFECATE_PICKER_OPEN'
// export const SELF_HELP_DEFECATE_DRUG_PICKER_OPEN 	  = 'SELF_HELP_DEFECATE_DRUG_PICKER_OPEN'
// export const SELF_HELP_STOOL_CONSISTENCY_PICKER_OPEN  = 'SELF_HELP_STOOL_CONSISTENCY_PICKER_OPEN'
// export const SELF_HELP_HEIGHT_CHANGE 				  = 'SELF_HELP_HEIGHT_CHANGE'
// export const SELF_HELP_WEIGHT_CHANGE 				  = 'SELF_HELP_WEIGHT_CHANGE'
// export const SELF_HELP_DIET_CHECKBOX_CHANGE 		  = 'SELF_HELP_DIET_CHECKBOX_CHANGE'
// export const SELF_HELP_SWALLOWING_CHECKBOX_CHANGE 	  = 'SELF_HELP_SWALLOWING_CHECKBOX_CHANGE'
// export const SELF_HELP_DYSSOMNIA_CHECKBOX_CHANGE 	  = 'SELF_HELP_DYSSOMNIA_CHECKBOX_CHANGE'
// export const SELF_HELP_ASSITANCE_TOOL_CHECKBOX_CHANGE = 'SELF_HELP_ASSITANCE_TOOL_CHECKBOX_CHANGE'
// export const SELF_HELP_PREFERENCE_SWITCH_CHANGE 	  = 'SELF_HELP_PREFERENCE_SWITCH_CHANGE'
// export const SELF_HELP_DYSSOMNIA_SWITCH_CHANGE 		  = 'SELF_HELP_DYSSOMNIA_SWITCH_CHANGE'
// export const SELF_HELP_SLEEP_AID_SWITCH_CHANGE 		  = 'SELF_HELP_SLEEP_AID_SWITCH_CHANGE'
// export const SELF_HELP_ASSITANCE_SWITCH_CHANGE 		  = 'SELF_HELP_ASSITANCE_SWITCH_CHANGE'
// 
// // 体格检查
// export const PHYSICAL_CONSCIOUSNESS_PICKER_OPEN 	 = 'PHYSICAL_CONSCIOUSNESS_PICKER_OPEN'
// export const PHYSICAL_LANGUAGE_PICKER_OPEN 			 = 'PHYSICAL_LANGUAGE_PICKER_OPEN'
// export const PHYSICAL_PHYSICAL_ACTIVITY_PICKER_OPEN  = 'PHYSICAL_PHYSICAL_ACTIVITY_PICKER_OPEN'
// export const PHYSICAL_SHAPES_PICKER_OPEN 			 = 'PHYSICAL_SHAPES_PICKER_OPEN'
// export const PHYSICAL_SKIN_CHECKBOX_CHANGE 			 = 'PHYSICAL_SKIN_CHECKBOX_CHANGE'
// export const PHYSICAL_SHAPES_UNUSUAL_CHECKBOX_CHANGE = 'PHYSICAL_SHAPES_UNUSUAL_CHECKBOX_CHANGE'
// export const PHYSICAL_WHEEL_CHAIR_CHECKBOX_CHANGE	 		 = 'PHYSICAL_WHEEL_CHAIR_CHECKBOX_CHANGE'
// export const PHYSICAL_WHEEL_CHAIR_LABEL_CLICK 				 = 'PHYSICAL_WHEEL_CHAIR_LABEL_CLICK'
// export const PHYSICAL_WALKING_FRAMES_CHECKBOX_CHANGE 		 = 'PHYSICAL_WALKING_FRAMES_CHECKBOX_CHANGE'
// export const PHYSICAL_WALKING_FRAMES_LABEL_CLICK 			 = 'PHYSICAL_WALKING_FRAMES_LABEL_CLICK'
// export const PHYSICAL_HAND_CRUTCH_SINGLE_CHECKBOX_CHANGE 	 = 'PHYSICAL_HAND_CRUTCH_SINGLE_CHECKBOX_CHANGE'
// export const PHYSICAL_HAND_CRUTCH_SINGLE_LABEL_CLICK 		 = 'PHYSICAL_HAND_CRUTCH_SINGLE_LABEL_CLICK'
// export const PHYSICAL_HAND_CRUTCH_DOUBLE_CHECKBOX_CHANGE 	 = 'PHYSICAL_HAND_CRUTCH_DOUBLE_CHECKBOX_CHANGE'
// export const PHYSICAL_HAND_CRUTCH_DOUBLE_LABEL_CLICK 		 = 'PHYSICAL_HAND_CRUTCH_DOUBLE_LABEL_CLICK'
// export const PHYSICAL_AXILLARY_CRUTCH_SINGLE_CHECKBOX_CHANGE = 'PHYSICAL_AXILLARY_CRUTCH_SINGLE_CHECKBOX_CHANGE'
// export const PHYSICAL_AXILLARY_CRUTCH_SINGLE_LABEL_CLICK 	 = 'PHYSICAL_AXILLARY_CRUTCH_SINGLE_LABEL_CLICK'
// export const PHYSICAL_AXILLARY_CRUTCH_DOUBLE_CHECKBOX_CHANGE = 'PHYSICAL_AXILLARY_CRUTCH_DOUBLE_CHECKBOX_CHANGE'
// export const PHYSICAL_AXILLARY_CRUTCH_DOUBLE_LABEL_CLICK 	 = 'PHYSICAL_AXILLARY_CRUTCH_DOUBLE_LABEL_CLICK'
// export const PHYSICAL_ELBOW_CRUTCH_SINGLE_CHECKBOX_CHANGE 	 = 'PHYSICAL_ELBOW_CRUTCH_SINGLE_CHECKBOX_CHANGE'
// export const PHYSICAL_ELBOW_CRUTCH_SINGLE_LABEL_CLICK 		 = 'PHYSICAL_ELBOW_CRUTCH_SINGLE_LABEL_CLICK'
// export const PHYSICAL_ELBOW_CRUTCH_DOUBLE_CHECKBOX_CHANGE 	 = 'PHYSICAL_ELBOW_CRUTCH_DOUBLE_CHECKBOX_CHANGE'
// export const PHYSICAL_ELBOW_CRUTCH_DOUBLE_LABEL_CLICK 		 = 'PHYSICAL_ELBOW_CRUTCH_DOUBLE_LABEL_CLICK'
// export const PHYSICAL_ORTHOSIS_SWITCH_CHANGE 		 = 'PHYSICAL_ORTHOSIS_SWITCH_CHANGE'
// export const PHYSICAL_PROSTHESIS_SWITCH_CHANGE 		 = 'PHYSICAL_PROSTHESIS_SWITCH_CHANGE'
// export const PHYSICAL_VAS_SWITCH_CHANGE 			 = 'PHYSICAL_VAS_SWITCH_CHANGE'
// export const PHYSICAL_PAINRELIEF_SWITCH_CHANGE 		 = 'PHYSICAL_PAINRELIEF_SWITCH_CHANGE'
// export const PHYSICAL_DELETE_SKIN_ITEM				 = 'PHYSICAL_DELETE_SKIN_ITEM'
// export const SKIN_ITEM_STAGE_PICKER_OPEN			 = 'SKIN_ITEM_STAGE_PICKER_OPEN'
// export const SKIN_ITEM_SUBMIT						 = 'SKIN_ITEM_SUBMIT'
// export const SKIN_ITEM_RETURN_SKINLIST				 = 'SKIN_ITEM_RETURN_SKINLIST'
// export const SKIN_ITEM_FORM_RESET					 = 'SKIN_ITEM_FORM_RESET'
// 
// // 心理社会
// export const PSYCHO_SOCIAL_VIEW_POINT_PICKER_OPEN 		 = 'PSYCHO_SOCIAL_VIEW_POINT_PICKER_OPEN'
// export const PSYCHO_SOCIAL_CONCERNS_SWITCH_CHANGE 		 = 'PSYCHO_SOCIAL_CONCERNS_SWITCH_CHANGE'
// export const PSYCHO_SOCIAL_MENTAL_CHECKBOX_CHANGE 		 = 'PSYCHO_SOCIAL_MENTAL_CHECKBOX_CHANGE'
// export const PSYCHO_SOCIAL_CONCERNS_NOTE_CHECKBOX_CHANGE = 'PSYCHO_SOCIAL_CONCERNS_NOTE_CHECKBOX_CHANGE'
// 
// // 护理要点
// export const MAIN_POINTS_NURSING_POINT_CHECKBOX_CHANGE = 'MAIN_POINTS_NURSING_POINT_CHECKBOX_CHANGE'











export const INPATIENT_NOTIFY_DOCTOR_SWITCH_CHANGE = 'INPATIENT_NOTIFY_DOCTOR_SWITCH_CHANGE'
export const INPATIENT_CONSCIOUSNESS_PICKER_OPEN = 'INPATIENT_CONSCIOUSNESS_PICKER_OPEN'
export const INPATIENT_COMMUNICATION_PICKER_OPEN = 'INPATIENT_COMMUNICATION_PICKER_OPEN'
export const INPATIENT_PHYSICAL_ACTIVITY_PICKER_OPEN = 'INPATIENT_PHYSICAL_ACTIVITY_PICKER_OPEN'
export const INPATIENT_SWALLOWING_PICKER_OPEN = 'INPATIENT_SWALLOWING_PICKER_OPEN'
export const INPATIENT_VISION_PICKER_OPEN = 'INPATIENT_VISION_PICKER_OPEN'
export const INPATIENT_HEARING_PICKER_OPEN = 'INPATIENT_HEARING_PICKER_OPEN'
export const INPATIENT_SKIN_PICKER_OPEN = 'INPATIENT_SKIN_PICKER_OPEN'
export const INPATIENT_CATHETER_SWITCH_CHANGE = 'INPATIENT_CATHETER_SWITCH_CHANGE'
export const INPATIENT_ALLERGIC_SWITCH_CHANGE = 'INPATIENT_ALLERGIC_SWITCH_CHANGE'

export const INPATIENT_HOSPITALIZED_TYPE_PICKER_OPEN = 'INPATIENT_HOSPITALIZED_TYPE_PICKER_OPEN'
export const INPATIENT_HOBBY_PICKER_OPEN = 'INPATIENT_HOBBY_PICKER_OPEN'
export const INPATIENT_DIET_PICKER_OPEN = 'INPATIENT_DIET_PICKER_OPEN'
export const INPATIENT_URINATION_WAYS_PICKER_OPEN = 'INPATIENT_URINATION_WAYS_PICKER_OPEN'
export const INPATIENT_DEFECATION_WAYS_PICKER_OPEN = 'INPATIENT_DEFECATION_WAYS_PICKER_OPEN'
export const INPATIENT_SELF_CARE_PICKER_OPEN = 'INPATIENT_SELF_CARE_PICKER_OPEN'