export const NOW_INIT						 = 'NOW_INIT'
export const SET_FALL_SUPERVISOR_FOLLOW_NAME = 'SET_FALL_SUPERVISOR_FOLLOW_NAME'
export const SET_FALL_SUPERVISOR_CONTENT 	 = 'SET_FALL_SUPERVISOR_CONTENT'

export const PICKER_CONFIRM 						  = 'PICKER_CONFIRM'
export const HEAD_NURSE_NAME_PICKER_OPEN 			  = 'HEAD_NURSE_NAME_PICKER_OPEN'
export const FALL_SUPERVISOR_TYPE_PICKER_OPEN 		  = 'FALL_SUPERVISOR_TYPE_PICKER_OPEN'
export const FALL_SUPERVISOR_INTERVENTION_PICKER_OPEN = 'FALL_SUPERVISOR_INTERVENTION_PICKER_OPEN'
export const FALL_SUPERVISOR_OUTCOME2_PICKER_OPEN 	  = 'FALL_SUPERVISOR_OUTCOME2_PICKER_OPEN'

export const FALL_SUPERVISOR_FALL_SWITCH_CHANGE   = 'FALL_SUPERVISOR_FALL_SWITCH_CHANGE'
export const FALL_SUPERVISOR_OUTCOME2_DATE_CHANGE = 'FALL_SUPERVISOR_OUTCOME2_DATE_CHANGE'
