export const NURSINGLIST_SHOW   = 'NURSINGLIST_SHOW'
export const NURSINGLIST_DELETE = 'NURSINGLIST_DELETE'
export const SET_IS_FROM_SUBMIT_TRUE  = 'SET_IS_FROM_SUBMIT_TRUE'
export const SET_IS_FROM_SUBMIT_FALSE = 'SET_IS_FROM_SUBMIT_FALSE'