export const GET_TEMPERATURE_LIST 	 = 'GET_TEMPERATURE_LIST'
export const TEMPERATURE_LIST_DELETE = 'TEMPERATURE_LIST_DELETE'
export const SET_IS_FROM_SUBMIT_TRUE  = 'SET_IS_FROM_SUBMIT_TRUE'
export const SET_IS_FROM_SUBMIT_FALSE = 'SET_IS_FROM_SUBMIT_FALSE'